package color

import "github.com/charmbracelet/lipgloss"

func New(color string) lipgloss.Color {
	return lipgloss.Color(color)
}

const (
	// Standard colors
	Black         = lipgloss.Color("0")
	Red           = lipgloss.Color("1")
	Green         = lipgloss.Color("2")
	Yellow        = lipgloss.Color("3")
	Blue          = lipgloss.Color("4")
	Magenta       = lipgloss.Color("5")
	Cyan          = lipgloss.Color("6")
	White         = lipgloss.Color("7")
	BrightBlack   = lipgloss.Color("8")
	BrightRed     = lipgloss.Color("9")
	BrightGreen   = lipgloss.Color("10")
	BrightYellow  = lipgloss.Color("11")
	BrightBlue    = lipgloss.Color("12")
	BrightMagenta = lipgloss.Color("13")
	BrightCyan    = lipgloss.Color("14")
	BrightWhite   = lipgloss.Color("15")

	// 6x6x6 Color cube (16-231)
	Maroon      = lipgloss.Color("16")
	DarkRed     = lipgloss.Color("17")
	DarkBlue    = lipgloss.Color("18")
	DarkMagenta = lipgloss.Color("19")
	DarkGreen   = lipgloss.Color("22")
	OliveGreen  = lipgloss.Color("28")
	DarkCyan    = lipgloss.Color("30")
	Teal        = lipgloss.Color("37")
	NavyBlue    = lipgloss.Color("38")
	SlateBlue   = lipgloss.Color("54")
	SkyBlue     = lipgloss.Color("81")
	SpringGreen = lipgloss.Color("48")
	LimeGreen   = lipgloss.Color("82")
	Aquamarine  = lipgloss.Color("87")
	MediumBlue  = lipgloss.Color("21")
	Violet      = lipgloss.Color("90")
	Pink        = lipgloss.Color("200")
	HotPink     = lipgloss.Color("205")
	DeepPink    = lipgloss.Color("197")
	LightPink   = lipgloss.Color("217")
	Orchid      = lipgloss.Color("170")
	Plum        = lipgloss.Color("176")
	Gold        = lipgloss.Color("220")
	Orange      = lipgloss.Color("214")
	Coral       = lipgloss.Color("209")
	Salmon      = lipgloss.Color("216")
	Peach       = lipgloss.Color("215")
	LightYellow = lipgloss.Color("229")
	Khaki       = lipgloss.Color("228")
	Ivory       = lipgloss.Color("230")
	WhiteSmoke  = lipgloss.Color("231")

	// Grayscale ramp (232-255)
	Gray0  = lipgloss.Color("232")
	Gray3  = lipgloss.Color("233")
	Gray7  = lipgloss.Color("234")
	Gray11 = lipgloss.Color("235")
	Gray15 = lipgloss.Color("236")
	Gray19 = lipgloss.Color("237")
	Gray23 = lipgloss.Color("238")
	Gray27 = lipgloss.Color("239")
	Gray30 = lipgloss.Color("240")
	Gray35 = lipgloss.Color("241")
	Gray39 = lipgloss.Color("242")
	Gray42 = lipgloss.Color("243")
	Gray46 = lipgloss.Color("244")
	Gray50 = lipgloss.Color("245")
	Gray54 = lipgloss.Color("246")
	Gray58 = lipgloss.Color("247")
	Gray62 = lipgloss.Color("248")
	Gray66 = lipgloss.Color("249")
	Gray70 = lipgloss.Color("250")
	Gray74 = lipgloss.Color("251")
	Gray78 = lipgloss.Color("252")
	Gray82 = lipgloss.Color("253")
	Gray85 = lipgloss.Color("254")
	Gray89 = lipgloss.Color("255")
)
